const uf = [
  { areviacao: 'AC', estado: 'Acre' },
  { areviacao: 'AL', estado: 'Alagoas' },
  { areviacao: 'AP', estado: 'Amapá' },
  { areviacao: 'AM', estado: 'Amazonas' },
  { areviacao: 'BA', estado: 'Bahia' },
  { areviacao: 'CE', estado: 'Ceará' },
  { areviacao: 'DF', estado: 'Distrito Federal' },
  { areviacao: 'ES', estado: 'Espírito Santo' },
  { areviacao: 'GO', estado: 'Goiás' },
  { areviacao: 'MA', estado: 'Maranhão' },
  { areviacao: 'MT', estado: 'Mato Grosso' },
  { areviacao: 'MS', estado: 'Mato Grosso do Sul' },
  { areviacao: 'MG', estado: 'Minas Gerais' },
  { areviacao: 'PA', estado: 'Pará' },
  { areviacao: 'PB', estado: 'Paraíba' },
  { areviacao: 'PR', estado: 'Paraná' },
  { areviacao: 'PE', estado: 'Pernambuco' },
  { areviacao: 'PI', estado: 'Piauí' },
  { areviacao: 'RJ', estado: 'Rio de Janeiro' },
  { areviacao: 'RN', estado: 'Rio Grande do Norte' },
  { areviacao: 'RS', estado: 'Rio Grande do Sul' },
  { areviacao: 'RO', estado: 'Rondônia' },
  { areviacao: 'RR', estado: 'Roraima' },
  { areviacao: 'SC', estado: 'Santa Catarina' },
  { areviacao: 'SP', estado: 'São Paulo' },
  { areviacao: 'SE', estado: 'Sergipe' },
  { areviacao: 'TO', estado: 'Tocantins' },
];

export default uf;
